### ISSUE TITLE
Possible bug in testcase.php _backup_hooks()

### ISSUE THREAD

**Issue by ChrisFlannagan** [lucatume/wp-browser#108]
I'm receiving the following error:

Fatal error: __clone method called on non-object in /app/public/dev/tests/vendor/lucatume/wp-browser/src/includes/testcase.php on line 244

In trying to track down what I could be doing wrong in my test I did a var dump in debug mode.  Seems it's trying to perform clone on an array.  I'm using php 5.6 on this project but as far as I know the __clone() is only on objects.  Here's the var dump of $hook_object

```
/app/public/dev/tests/vendor/lucatume/wp-browser/src/includes/testcase.php:244:
array(1) {
  [10] =>
  array(1) {
    '_wp_die_handler_filter' =>
    array(2) {
      'function' =>
      string(22) "_wp_die_handler_filter"
      'accepted_args' =>
      int(1)
    }
  }
}
```

**Comment by lucatume** [comment]
The issue here is that WordPress now [uses objects](https://core.trac.wordpress.org/browser/trunk/src/wp-includes/plugin.php#L106) to manage the filters where it used, until version `4.7`, [arrays](https://core.trac.wordpress.org/browser/branches/4.6/src/wp-includes/plugin.php#L103); see [code here](https://developer.wordpress.org/reference/classes/wp_hook/).

**Comment by lucatume** [comment]
I've provided a *probable* fix in the `fix-issue-108` branch.
