### ISSUE TITLE
WPLoader for real unit tests

### ISSUE THREAD

**Issue by sformisano** [lucatume/wp-browser#111]
Hey Luca,

I wanted to ask if your library provides a simple way to do real basic unit tests, i.e. something like a subset of WPLoader that doesn't require a database connection.

If there isn't I'll keep using wpunit for both unit and integration tests.

p.s. going step by step through your guide here: http://codeception.com/for/wordpress

I wanted to let you know that this command complains about the integration suite not being loaded:

`codecept generate:wpunit integration "Acme\SomeClass"`

what worked for me was either referencing the wpunit suite:

`codecept generate:wpunit wpunit "Acme\SomeClass"`

or creating a standard unit test like this:

`codecept generate:test unit "Acme\SomeClass"`

and then adding the WPLoader module to the `unit.suite.yml` file.

Plus, the command references the integration suite, but the read more link at the end of the section points to the codeception unit testing guide.

All minor details, but I'm sure this can be confusing for some people so I figured I'd let you know.

Cheers,
Salvatore

**Comment by lucatume** [comment]
Again: thanks for pointing it out, Iwill update the Readme

**Comment by lucatume** [comment]
Hi, I've now had time to get back to this:

>I wanted to ask if your library provides a simple way to do real basic unit tests, i.e. something like a subset of WPLoader that doesn't require a database connection.

No, wp-browser does not come with anything like that; the reason being that if you need a WordPress function in the code you are testing then you need to load WordPress and WordPress will not load without a database connection.
The solution is to use a WP-Loader powered test for unit **and** integration tests, as you are doing or to use, in unit tests, an home-grown or library based solution to "fake" the functions you code is using.

E.g.: I need to test this simple class:

```php
class MyAdmin {
	public function url($path = null, array $args = [], $scheme = 'admin'){
		return empty($args) ?
			admin_url($path, $scheme)
			: add_query_arg($args, admin_url($path, $scheme));
	}
}
```

Specifically I want to test the `url` method; since it uses the `admin_url` function I will need to either:
* load WordPress (using WP-Loader) and have that function defined in my tests
* defined the `admin_url` function, for the purpose of tests, in the unit tests `tests/unit/_bootstrap.php` file

The first option is known, the second might consist in:
* homegrown solution like:
	* in `test/unit/_bootstrap.php` file:
		```php
		function admin_url($path = '', $scheme = 'admin'){
			global $admin_url_mock;
			return is_callable($admin_url_mock) ?
				$admin_url_mock
				: call_user_func($admin_url_mock, $path, $scheme);
		}
		```
	* in the test file:
		```php
		function test_url(){
			global $admin_url_mock;
			$admin_url_mock = 'http://example.com/admin';
			
			$myAdmin = new MyAdmin();
			
			$this->assertEquals('http://example.com/admin/foo', $myAdmin->url('foo'));
		}
		```
* use a library that takes that away from your code like [function-mocker-le](https://github.com/lucatume/function-mocker-le) or similar; there are others:
	```php
	function test_url(){
		tad\FunctionMockerLe\define('admin_url', function($path){
			return 'http://example.com/' . $path;
		});
		
		$myAdmin = new MyAdmin();
		
		$this->assertEquals('http://example.com/admin/foo', $myAdmin->url('foo'));
	}
	```
	
Sorry for the long, and maybe not that helpful, answer but this comes up quite often and it might help anyone else that is having the same issue in the future.

**Comment by sformisano** [comment]
No actually this is very helpful, your 0,02 on why db connection is required make a lot of sense, so thanks for pointing all of it out!

**Comment by lucatume** [comment]
On the same line as function-mocker is [BrainMonkey](https://github.com/Brain-WP/BrainMonkey).
