### ISSUE TITLE
Use tests database by default on acceptance.dist.yml and functional.dist.yml

### ISSUE THREAD

**Issue by Luc45** [lucatume/wp-browser#189]
`acception.dist.yml` and `functional.dist.yml` uses populator on regular DB by default, which can be dangerous.

It's an implementation detail that can be easily overlooked by someone installing wp-browser on an existing project, specially since `codecept init wpbrowser` asks you to create a test database, it's logical to assume that it will be used during tests. 

I can do a PR if you wish.

_Originally posted by @Luc45 in https://github.com/lucatume/wp-browser/issue_comments#issuecomment-435154398_

**Comment by lucatume** [comment]
I do agree with you that the verbiage in the documentation and in the unit template could be improved to make it clear what’s going to happen.
I’m not going to change the default behavior to use some default database though, for three reasons:
1. Default behaviors are hidden and the default behavior will soon become the behavior people will complain about. Since you have to set a config file to target a database I fele that, and more clarity during the bootstrap process, should do it. 
2. Wp-browser is a testing suite. No production database, or any database you care about, should ever be near anything that is about testing. Again I feel a warning is enough and I will add it in a PR.
3. Acceptance and functional are just names. I have many projects where those suites are not even set at all. Suites can contain a number of modules, among those WPDb (the “offender” here): any logic trying to smartly detect what database to use when would fall short if expectations, be a pain to override for users and be a nightmare to maintain. Codeception filosofo is one of configuration power and I want to keep it.

Next step: improve documentario and warn people.

**Comment by Luc45** [comment]
Allright, so, I would respectfully like to continue this discussion.

Here's the logs for the `codecept init wpbrowser` command:

![mintty_2018-11-02_13-17-29](https://user-images.githubusercontent.com/9341686/47927302-a8545480-dea1-11e8-8b8e-511ee6ed9b6f.png)

Read them as a first-time user, not know what you know.

Someone who's starting with wp-browser, won't understand the difference between WPLoader and WPDb. Specially because the first step states "Create the database used by the modules" - which leads to think that wp-browser will use TEST_* databases for running tests in all modules by default.

Having the tests run in two databases (WPDb and WPLoader) is confusing as default behavior. 

I think it's easier to explain that dump.sql will be imported in the test database every time a test runs.

If, however, the person wants to test on "regular" database, it's their choice, and they should change the YML to represent that behavior.

If you still disagree, I will happily accept your decision and you can close the issue.

The best,
Lucas

**Comment by Luc45** [comment]
I think I got why it works like this...

Acceptance and functional tests will run the live website in the browser, which uses regular database. If a record is inserted in test db, it will not show.

For it to work, WPBrowser would have to change database to TEST_* in runtime, right? Which is also kind of confusing...

**Comment by lucatume** [comment]
You are correct: typically the WpBrowser, or WpWebDriver suites will hit a "real" site you could visit as a user. To have any effect on that site WPDb must manipulate that site database and, from that, disaster might ensue.
Many users will use that same website to keep their valuable test information or, worse, use their production site to run the tests.

**Comment by lucatume** [comment]
Did not mean to close this (fat fingers). 
I will post a preview of the improved disclaimer/warning that's coming in version `2.2`.

**Comment by lucatume** [comment]
Ok, this is the what you will see in version 2.2 of wp-browser when running the `init` command: 
<img width="899" alt="screenshot 2018-11-05 at 21 32 39" src="https://user-images.githubusercontent.com/2749650/48024974-6e55ad80-e142-11e8-9aad-3a832927e062.png">
<img width="1321" alt="screenshot 2018-11-05 at 21 32 57" src="https://user-images.githubusercontent.com/2749650/48024979-70b80780-e142-11e8-9431-3db03193f4fc.png">
These two seems to provide enough warning, and in clear enough terms, to avoid misunderstandings.
@Luc45 let me know what you think about it.

**Comment by Luc45** [comment]
Hi Luca,

I think it's a valid effort to improve the bootstrap script, however, perhaps we could try for a friendlier approach, since the aim is to provide a low entry barrier for WordPress testing, we don't want to scare developers away with flashy red warnings.

Perhaps something like:

> Welcome to WP-Browser, a complete test suite for WordPress based on CodeCeption and PHPUnit!
> 
> This script will guide you through the initial setup for this project.
> 
> Warning: WP-Browser is meant to run on DEVELOPMENT servers only. Before you begin, make sure you have a backup of your project, including your DATABASE!!!!!!!
> 
> If you are starting with WP-Browser, follow this guide:
> https://www.testdrivenwordpress.com/getting-started
> 
> `[Regular codecept init wpbrowser script here]`

In the Getting Started guide,  we can explain about DB_* and TEST_DB_*, I mean, this is only going to be necessary for the first-timers initing wp-browser, so if we could keep the init clean and unpolluted, I think it could be better in the long-run.
