### ISSUE TITLE
Erratic tests results using add_filter and WP_FileSystem

### ISSUE THREAD

**Issue by Luc45** [lucatume/wp-browser#208]
Hi Luca!

I would like to test my code using `add_filter()`.

For that, I am creating a file `mu-plugin/a.php` in my tests with the filter and asserting the desired behavior:

```php
/**
 * Test RouteConditional works with array
 *
 * @param FunctionalTester $I
 * @throws \Codeception\Exception\ModuleException
 */
public function it_should_route_a_request_by_array(FunctionalTester $I)
{
    $code = <<<PHP
class Foo {
    public function bar() {
        echo 'Is bar!';
    }
}

add_filter('mww_conditional_routes', function(\$routes) {
    \$routes[] = [
        'conditional_tag' => 'is_front_page',
        'handler' => ['Foo', 'Bar']
    ];
    return \$routes;
});
PHP;
    $I->haveMuPlugin('a.php', $code);
    $I->amOnPage('/');

    $I->see('Is bar!');
}
```

I have three tests in place using this approach:
https://github.com/Luc45/ModernWordPressWebsite/blob/master/mww/tests/functional/MWW/Routing/RouteConditionalCest.php?

However, the tests fail randomly between them.

### Debugging so far:

- If I add breakpoints on `$I->amOnPage('/');` and tail "a.php", I can see that it is being updated correctly. _(However, this can be misleading, as the breakpoint gives time for the file to be released in case of a micro-time lock during the tests)_
- If I test each method individually, they all work.
- If I test the class or the suite, they fail randomly.
- If I create `a.php` manually with the contents of `$code` and view it in the browser, it works.

### My suspects:

- Write file lock on `a.php` between one test and another, causing the next test to test `a.php` with the contents of the previous test.
- Test sharing WordPress context of previous test, which had already been filtered.

### Results of failed tests:

Taking this order of execution:

1. it_should_route_a_request_by_array
2. it_should_route_a_request_by_string
3. it_should_route_a_request_by_closure

I got this error:
```
Failed asserting that  on page /
--> Route tested!
--> contains "Closure is working!".
```

Method number 3 fails by seeing results provided by method number 2. Method number 2 occasionaly fails by seeing results provided by method number 1.

I don't know if this is relevant, but I use Vagrant with NFS enabled in Windows 10. (SSD)

### Final notes

Come to think about it, this issue might be related to the implementation of DI container. It started ocurring more or less after it's implementation. Both `bind` and `singleton` methods on router classes gives the same results above. I think that, to understand if DI can affect this, I need to understand if each test is an isolated request.

**Comment by Luc45** [comment]
### Update
In this precise moment tests are running. I haven't changed anything, which indicates a subtle issue.

**Comment by lucatume** [comment]
From the look of it, it seems this issue is related with a "slow" writing and unlinking.
If you are using a virtualized solution it could take time for the changes to propagate from your host machine to the guest one; with an example:

On the host machine WordPress is located at `/Users/Lucas/sites/wp`; during the tests the WPFileSystem module will go and first add, then remove, the `a.php` file from the `/Users/Lucas/sites/wp/wp-content/mu-plugins` folder. This change is immediate on the host machine filesystem but the virtualization solution will have to replicate the change on the guest machine, i.e. the virtual machine.
Some solutions are instantaneous (e.g. Docker), some are slower (e.g. Virtualbox) if not configured very well or if not allocated a good amount of cpu/RAM.
The solution could be, in this order:
1. in place of calling all mu-plugins `a.php` call them with a unique name; this has helped
2. find ways to speed up the virtualized solution (search it online depending on your solution)

Solution 1 is the most future-proof one as it's the one that could prove being a bit more CI-proof. In the context of CIs the virtual machine might not have the horse power no matter what.

Let me know if this helps.

**Comment by Luc45** [comment]
@lucatume calling mu-plugins with different names solved the issue - or at least almost. I have other tests that must write to a specific file in the system, and those still fails randomly, because I can't change the file name.

Indeed it seems a writing issue with Vagrant. My Vagrant setup should be pretty fast, with 4GB Ram dedicated to it and a couple i7 CPU cores, running entirely on SSD using NFS technology, which should be fast.

**Comment by Luc45** [comment]
Closing this issue and we found out this is related to write speed of Vagrant. Thanks @lucatume!
