### ISSUE TITLE
WpLoader loadOnly Clarification

### ISSUE THREAD

**Issue by halmos** [lucatume/wp-browser#243]
**Did you search the documentation first?**
Yes

**What do you think is missing from the documentation?**
I am not able to discern if running with `loadOnly: true` on the WPLoader config should clear the wp db. I expected setting `loadOnly: true` would preserve the wp db as well as retain any changes made during testing, but running my test seems to indicate that the WP Db is cleared either before or after the test is run. 

Is my observed behavior the expected outcome? If so, it would be great to add some further detail in the WPLoader module about this. 

Alternatively, is there a way to use WPLoader with `loadOnly: true` so that the Db is left unaffected?

thank you!

**Comment by lucatume** [comment]
I remember, looking at the config files you posted in https://github.com/lucatume/wp-browser/issues/241, that you're using the `WPDb` and `WPLoader` module.
The first has `populate` and `cleanup` set to `false`, and will hence not clean or populate the database; while the second has `loadOnly` set to `true`.

It's an unusual setup for an integration (WPUnit) test; usually the `WPDb` module is not used as one can use WordPress methods to manipulate the database; could you show an example of what you're trying to do in the tests that requires the `WPDb` module? 

I feel like the solution might be this:
1. do not use the `WPDb` module at all
2. use the `WPLoader` module with `loadOnly: false` (or not set the value)
3. use WPLoader factories to setup the test fixtures.
4. use a different database (say `integration`) for integration tests and one for acceptance tests.

**Comment by halmos** [comment]
Hi, thank you for your time and assistance!

We have a slightly unusual wordpress testing scenario in that we are not aiming to test a generic theme, but rather a monolithic sight built on wordpress. In other words, i need to be able to test the theme functions with a real sql database pulled from the deployed sight into a Local by Flywheel dev environment. 

From reading of the Levels of Testing section in the docs, I believe what we are aiming to do is a hybrid of Integration Tests and Wordpress unit tests. ie. We wish to perform tests by calling theme class methods with the real db loaded. In our ideal testing environment we would be able to perform non-destructive automated testing on the Local by Flywheel site instance using the existing DB. 

My understanding is that we need to use the WPLoader module in order for the tests to make direct calls on the theme's functions. Is that correct? Based on that understanding, we are looking for a way to perform the WpUnit tests without the clearing out the Local by Flywheel site's db. 

thanks again

**Comment by lucatume** [comment]
Ok, so let me try to walk through your setup to see if I got it correctly:

1. you have manually set up a complex database fixture; in this case in a Local by Flywheel database
2. in your **integration** tests you want to use WordPress, and your theme/plugins, functions, classes and methods to make assertions (more on that later).
3. In your tests you do not want to modify (create, update, delete) the database in any way, just read from it.

If this is what you need to do, then you do not need the `WPDb` module at all; after all: if it's not loading a database dump of any sort and you're not using its methods you won't need it. I'd remove that from the configuration.

Since the `WPUnitTestCase` is a wrapper of the Core Suite test case it's really meant to work by wiping the database between tests to allow each test method to "start fresh". You do not need this: you just need to load WordPress on a ready database.

Before I provide you with the code to do what you're trying to do please take a moment to explore, in the context of a `WPTestCase` the factories, you can invoke them using `static::factory()->post`, e.g. is for posts. They might cover a lot of mileage and they do provide a quick way to setup complex database fixtures without dropping a beat.

I would create a dedicated suite:
```bash
vendor/bin/codecept g:suite template_tags
```

Configure that suite to use the `WPLoader` module (I'm editing the `tests/template_tags.suite.yml` file here):
```yaml
actor: Template_tagsTester
modules:
    enabled:
        - \Helper\Template_tags
        - WPLoader
    config:
        WPLoader:
            loadOnly: true
            wpRootFolder: "~/Local Sites/wp/app/public"
            dbName: local
            dbHost: "192.168.92.100:4006"
            dbUser: root
            dbPassword: root
```

And finally create simple test methods using Codeception:
```bash
vendor/bin/codecept g:test template_tags Post
```

I've manually, in my Local installation, created a post with the "A Test Post" and I'm relying on that post to be there to make the assertions below:

```php
class PostTest extends \Codeception\Test\Unit
{
	public function test_post_exists(){
			// This post was not created in the tests; but manually, in the db used to bootstrap WP.
			$a_test_post = get_page_by_title('A Test Post', OBJECT, 'post');

			$this->assertInstanceOf(\WP_Post::class, $a_test_post);
			$this->assertEquals('A Test Post', $a_test_post->post_title);
	}
}
```

I can run this test successfully:

```
$> cr template_tags
Codeception PHP Testing Framework v3.0.1
Powered by PHPUnit 8.1.5 by Sebastian Bergmann and contributors.
Running with seed:


Template_tags Tests (1) ----------------------------------------------------------------------------------------------------
✔ PostTest: Test_post_exists (0.03s)
----------------------------------------------------------------------------------------------------------------------------


Time: 358 ms, Memory: 28.00 MB

OK (1 test, 2 assertions)
```

**Comment by halmos** [comment]
That's very helpful - thank you! I was under the mistaken impression that `WPLoader` was clearing the DB, not the `WPUnitTestCase` class.  It might be worth considering a test suite generator for this type of application..?

Thanks again!
