### ISSUE TITLE
[BUG] Db class is not imported

### ISSUE THREAD

**Issue by dingo-d** [lucatume/wp-browser#360]
**Environment**
OS: Mac Os
PHP version: 7.2.24
Installed Codeception version: 4.1.4
Installed wp-browser version: 2.4.0
WordPress version: 5.4
Local development environment: Valet+ and VVV
WordPress structure and management: default

You missed importing the `Db` class from Codeception in the `src/Codeception/Module/WPDb.php`

> Fatal error: Class 'Codeception\Module\Db' not found in /Users/denis.zoljom/vagrant-local/www/infinum/dev-portal/public_html/wp-content/plugins/developer-portal/vendor/lucatume/wp-browser/src/Codeception/Module/WPDb.php on line 32

**Comment by dingo-d** [comment]
Also, it seems that the necessary libraries weren't pulled when I did `composer require --dev lucatume/wp-browser`. I see that I should have `codeception/module-db` installed, but I don't see it.

**Comment by BrianHenryIE** [comment]
I needed in `composer.json`:
```
        "lucatume/wp-browser": "2.4.2",
        "voku/portable-ascii": "dev-master",
        "codeception/module-db": "^1.0.0",
        "codeception/module-phpbrowser": "^1.0.0"
```
before `vendor/bin/codecept run acceptance` worked.

As you say, there are a lot of `codeception/codeception suggests installing...` and `lucatume/wp-browser suggests installing...` in Composer's output.

**Comment by lucatume** [comment]
I've not gone with a major version since wp-browser `2.4`, the version that added Codeception 4.0 compatibility, is not a breaking change.
I did a lot of work to avoid breaking back-compatibility.

What I'm thinking of improving is the following, though:

1. better messaging, not just an exception, when a Codeception module is mising
2. support for Codeception 4.0 requirements in the `codecept init wpbrowser` template
3. support for upgrades of existing installations using some separate binary

I've put that off to limit the scope of release 2.4 as the current solution, while clunky, is available.
