### ISSUE TITLE
[FEATURE REQUEST] Hide admin top bar in WPWebDriver to avoid miss-clicks

### ISSUE THREAD

**Issue by Luc45** [lucatume/wp-browser#408]
**Is your feature request related to a problem? Please describe.**
Yes. I want to run webdriver-driven tests, but sometimes the admin top bar gets in the way of what the driver is trying to click. For instance, let's say you are editing a post in the admin dashboard where the driver has to scroll down to fill some fields (as a meta box bellow the content in the classic editor), then the driver tries to click the "Publish" button, it scrolls down to `#publish` but since there's the topbar it clicks it instead, thus failing the test.

**Describe the solution you'd like**
I'd like to suggest to hide the admin top bar by default when using `WPWebDriver`, and that the option `hideTopBar` is added to this suite for showing the admin bar. (optional, defaults to `true`)

**Describe alternatives you've considered**
I've hidden the top bar using a mu-plugin, but I imagine that this should be a common issue for folks, and not many of them have Selenium running a real browser to see the issue happening - some people might be running Selenium headless, which makes this issue harder to find out, which leads us to blame Luca, naturally.

**Comment by lucatume** [comment]
@Luc45 the issue here is that the top-bar is not hidden by default and this would cause a difference between what one sees with human eyes when manually checking the backend and what the web-driver sees.

Furthermore, there are tests where the admin bar is part of the test and removing it, especially by default, would be a back-incompatible change I'm not willing to make.

I think a more sophisticated fix is in order here, maybe reading the admin bar height and offsetting all `scrollTo` calls.
