### ISSUE TITLE
WP-CLI is a complex tool

### ISSUE THREAD

**Issue by szepeviktor** [lucatume/wp-browser#431]
Please consider directing users to use Phive or download the PHAR file to install WP-CLI.
It is a complex tool, it creates dependency problems.

I see your code needs some files from `wp-cli/wp-cli`, requiring only that package needs only 6 pkgs:

```
Package operations: 6 installs, 0 updates, 0 removals
  - Installing wp-cli/php-cli-tools (v0.11.11): Loading from cache
  - Installing wp-cli/mustangostang-spyc (0.6.3): Loading from cache
  - Installing symfony/finder (v5.1.3): Loading from cache
  - Installing rmccue/requests (v1.7.0): Loading from cache
  - Installing mustache/mustache (v2.13.0): Loading from cache
  - Installing wp-cli/wp-cli (v2.4.1): Loading from cache
```

Thank you for considering.

**Comment by lucatume** [comment]
@szepeviktor I'm not excluding it does cause problems, as any package with dependencies does, but I do not think requiring users to set up a development dependency manually would make for a better experience.

Are you running into a dependency issue caused by wp-cli? Would you mind sharing the issue details to debug a bit?

I've been thinking about embedding the phar version of wp-cli in the software for a bit, and see that as a possible path forward. There are additional issues that might be caused by this change, though, as loading wp-cli modules on a per-project level would become more difficult.

Can you think of another approach that would still keep the "wp-browser comes with wp-cli" experience intact without bringing along the issues you mention?

**Comment by szepeviktor** [comment]
> Can you think of another approach that would still keep the "wp-browser comes with wp-cli" experience intact without bringing along the issues you mention?

No.

I see we have to align our software to our users.

**Comment by lucatume** [comment]
I appreciate the feedback and brainstorming in any form: if at any later moment, you can come up with a solution to this issue, I would be happy to explore it and take a stab at it.

Thanks!

**Comment by szepeviktor** [comment]
> you can come up with a solution to this issue

Let's have only paid professional in the WordPress ecosystem :)
