### ISSUE TITLE
[FEATURE REQUEST] Publish GitHub Action

### ISSUE THREAD

**Issue by szepeviktor** [lucatume/wp-browser#442]
Hello Luca!
Do you plan/may I help to publish a [GH action](https://github.com/marketplace?type=actions&query=wordpress) that tests a plugin or theme?

From https://github.com/dingo-d/woo-solo-api-test-action/pull/3

**Comment by lucatume** [comment]
Hi @szepeviktor  I've not had the time to look into this, but I'm not shutting the door to anything.
In the last year I've set up GHA and wp-browser some 10 times or so and had to take different routes depending on the WP versions, PHP version, web-server and type of project.
What kind of solution are you thinking about? What configuration parameters would such an action consume?
I'm interested.

**Comment by szepeviktor** [comment]
Of course people should already have PHP set up.

- for theme and plugin repos only
- PHP should be set up
- the only input should be `WP_VERSION` environment variable
- tests should be is a certain directory
- all other things should be done by this GH action :)

**Comment by lucatume** [comment]
I would need to see an example yml GHA configuration file to be able to poke holes into it.
I cannot set it up now, but would very much like to explore this. 
I would also like the library provided set up to scaffold such action, something like the wp-cli plugin test scaffold command does.

**Comment by dingo-d** [comment]
There are some limitations to GH Actions. Initially, I wanted to just specify WP version, PHP version, and Node version as parameters that would be passed to the custom action itself, but that isn't possible

https://github.community/t/using-inputs-when-specifying-dockerfile-name-in-the-custom-docker-action/18504

I've stumbled upon some other issues, but cannot remember all of them atm, I don't know if they improved anything since the last time I've used them 🤷‍♂️ 

Having a custom action for wp-browser that could be used in plugins would be awesome tho 🙂 .

**Comment by szepeviktor** [comment]
PHP and NodeJS should be step **before** invoking this GH action.

**Comment by dingo-d** [comment]
Ideally yes, but since Docker is self-contained, I'm not 100% sure how to just run tests inside it without building the plugin inside (for which again I need PHP and Node). 

I might be missing some insight, but I haven't gone in-depth in checking how to overcome this issue.I should revisit this in a few weeks hopefully 🙂

**Comment by szepeviktor** [comment]
@lucatume Could you show me a plugin or theme here on GitHub that is properly written and uses wp-browser?

**Comment by lucatume** [comment]
Not one that is "vanilla" and does not come with so many modifications to the base set up not to blur the example, really. Or that is not private.

Regarding Docker: I try to avoid building it in GHA, at least I try to avoid building the costly part of copying the files over. Since the machine GHA runs on is a Ubuntu one, volume binding is fine.

The simpler stack I've used is the one where I use the default WordPress container (w/ Apache), bind in the plugins and themes I require, add a MariaDb database to the stack and use [a Codeception dedicated container I made](https://hub.docker.com/repository/docker/lucatume/codeception) to run Codeception tests.
There are a number of nuances to the stack, but that's the bulk of it, really.

In my perception, the "GitHub Actions" problem is, really, a "run wp-browser tests in Docker" problem. Once the solution is done, then it can be used in other CI systems too.

I will try to contribute an example `docker-compose.yml` file in this thread to tap into the collective mind later in the week.

**Comment by BrianHenryIE** [comment]
I have unit, wpunit, integration and WPBrowser acceptance tests running on GitHub Actions in workflows (i.e. not an "Action" as such, but you could create an Action from them):

https://github.com/BrianHenryIE/bh-wc-csp-condition-ip-address/

That project won't build locally for anyone because it pulls in from a private composer repository. The following one will (but hasn't as many Actions set up):

https://github.com/brianhenryie/bh-wp-autologin-urls

I have a starter project I use to set them up: https://github.com/brianhenryie/wordpress-plugin-boilerplate
I don't use Docker so don't have any insight around that.

**Comment by lucatume** [comment]
@BrianHenryIE that is interesting stuff you have there.

I will take inspiration from it while putting together a wp-browser GHA workflow file.

I would not like to make GHA "the" CI solution that wp-browser projects should use, but I would like to provide examples of how it could be set up for plugins, themes and sites in the documentation.

When that is done, then the process can be automated in the `init` phase with some interactivity and user questions.

**Comment by BrianHenryIE** [comment]
The WordPress Gutenberg repo has been working on a standard development Docker image (nothing to do with GA):

https://github.com/WordPress/gutenberg/issues/17724

https://github.com/WordPress/gutenberg/issues?q=is%3Aissue+wp-env
