### ISSUE TITLE
TEST_DB_NAME vs TEST_SITE_DB_NAME

### ISSUE THREAD

**Issue by alxvallejo** [lucatume/wp-browser#460]
What's the difference here? I just quickly ran through set up but now i need to tune the config so that it works with my Lando wordpress instance.

**Comment by lucatume** [comment]
If you look at your suites configuration files (`<suite>.suite.yml`) you will see placeholders like `%TEST_DB_NAME%` used to set up the suite configuration using an environment file.
That environment file is the `.env.testing` one (by default, might be different if you changed its name during the installation).
Since many set up the suites to use a "site DB" for acceptance, and a "test db" for integration testing (wp-unit) the setup will scaffold both.
So:
* `TEST_SITE_` is usually for acceptance and functional testing
* `TEST_` is usually for integration, wp-unit testing

But there's no obligation to follow those default.s

**Comment by Luc45** [comment]
My suggestion is that you create two databases:
1. `myproject_tests` -> `TEST_DB_NAME`
2. `myproject_site_tests` -> `TEST_SITE_DB_NAME`

By default, the first one will be used for wpunit tests, which are just UNIT tests for WordPress. This database can be empty, you don't have to import any kind of data to it. Any database query that happens in this DB will be a transaction that will be rolled-back between each test.

The second one is for running acceptance/webdriver tests. This means it's for a REAL TEST SITE that you can hit in your browser. This second database is persistent, so you have to generate a dump of your current site and save it on `tests/_data/dump.sql` so that the tests can import this dump and start the tests from a known state every time.

**Comment by lucatume** [comment]
@alxvallejo if this issue does not require further discussion or a fix, I would ask you to close it.
