### ISSUE TITLE
[BUG] Running unit and WpTestCase tests in one command leads to mysqli erros in wpdb.

### ISSUE THREAD

**Issue by calvinalkan** [lucatume/wp-browser#497]
I think I might have found a bug that is related to how dispatching handles event dispatching. 

Given the following two tests:

```php 
 namespace Tests\integration;

    use Codeception\TestCase\WPTestCase;


    class FooBarIntegrationTest extends WPTestCase
    {


   
        /** @test */
        public function foobar (){

              self::assertSame('foo', 'foo');

        }


    }

```

```php


 namespace Tests\unit;

    use Codeception\Test\Unit;

    class FoobarUnitTest extends Unit
    {


        /** @test */
        public function foobar () {

            self::assertSame('foo', 'foo');

        }


    }


```

Running `vendor/bin/codecept run tests` leads to the following error inside the wpdb class: 

```php

In ErrorHandler.php line 84:
                                                                          
  mysqli_query(): Couldn't fetch mysqli at ../wp-includes/wp-db.php:2058  

```

Running  `vendor/bin/codecept run unit` and `vendor/bin/codecept run integration` works fine as expected. 

After hours of debugging, I found out the root cause for this. 

After each test codeception will call this method. Even though the current test case is the `FoobarUnitTest` the `_teardownAfterClass` method for the `WpTestCase` is still registered as an event subscriber in codeception. 

```php

namespace Codeception\Subscriber;


class BeforeAfterTest implements EventSubscriberInterface
{
    
    protected function runHooks($hookName)
    {
        foreach ($this->hooks as $className => $hook) {
            foreach ($hook[$hookName] as $method) {
                if (is_callable([$className, $method])) {
                    call_user_func([$className, $method]);
                }
            }
        }
    }
}


```

This lead to ` _delete_all_data()` being called inside `WpTestCase` which then hits `wpdb->query`. 

This causes the described mysqli error. I was not able to debug my the mysqli error occurs yet but IMO it should not be called at all here. 

The test we run was a unit test that did not extend `WpTestCase`. Neither `_setUpBeforeClass` nor `_tearDownAfterClass` should be executed here. If you run these two tests together `WpTestCase`should only execute these methods once. Before and after `FooBarIntegrationTest`.  In reality, both are called two times. 

FIX: 

I'm not familiar with how codeception works under the hood, but to fix this temporarily for me I did the following. 

In `WpTestCase` add the following line at the start of `_setUp`

```php
 $GLOBALS['is_wp_integration_test'] = TRUE; 
 ```

In `_tearDown` at the following line at the start: 

``` php
unset($GLOBALS['is_wp_integration_test']);
```

Now we just check for this global inside the `_setUpBeforeClass` nor `_tearDownAfterClass` methods: 

```php 
  if ( ! isset($GLOBALS['is_wp_integration_test'])) {
            return;
        }
```

Console output before the fix: 

```Codeception PHP Testing Framework v4.1.20
Powered by PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

In ErrorHandler.php line 84:
                                                                          
  mysqli_query(): Couldn't fetch mysqli at ../wp-includes/wp-db.php:2058  
                                                                          

run [-o|--override OVERRIDE] [-e|--ext EXT] [--report] [--html [HTML]] [--xml [XML]] [--phpunit-xml [PHPUNIT-XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--bootstrap [BOOTSTRAP]] [--no-redirect] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--coverage-crap4j [COVERAGE-CRAP4J]] [--coverage-cobertura [COVERAGE-COBERTURA]] [--coverage-phpunit [COVERAGE-PHPUNIT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--seed SEED] [--no-artifacts] [--] [<suite> [<test>]]


Process finished with exit code 2
```

After the fix: 

```
Codeception PHP Testing Framework v4.1.20
Powered by PHPUnit 9.5.4 by Sebastian Bergmann and contributors.


Time: 00:01.070, Memory: 40.50 MB

OK (2 tests, 1 assertion)
Process finished with exit code 0
```

This is a quick working fix, but the underlying issue is with codeception setup here. All hooks from a test suite should be removed after the last test has run.

**Comment by lucatume** [comment]
Ah, old issue and there is not really much I can do about it due to WordPress love for side effects and global.
Due to all the places where WordPress is loaded (e.g. in Acceptance context with WPLoader `loadOnly: true`) this is really a rat-race that I've already tried to tackle creating more issues than I was resolving.

[See the documentation.](https://wpbrowser.wptestkit.dev/faq#can-i-run-all-my-tests-with-one-command)

Why is this not prevented at a code level? Because some are running more complex setups where this preventing of "run all the tests" is just too disruptive to perform.

While not ideal, you should run your suites one by one or build a batch command to do it, e.g. using [a Composer script](https://getcomposer.org/doc/articles/scripts.md) to run `composer run-script tests`.

**Comment by lucatume** [comment]
Your suggestion is a good one, though.
I would not mix unit tests and integration tests (any test case based on `WPTestsCase`) in my own code, but I would like to explore your suggestion and see what could come of it. If it turns out to be a low lift to support this, why not?

**Comment by calvinalkan** [comment]
Yea I get why you`d run them separately. Still annoying tho. My "fix" is working fine tho. Testing this for two days. 

Do you want me to commit a pr?. 

I'm maintaining a work of wp-browser, but the only changes I made are to the constant names in the .env.file. 

I renamed the database that gets flushed during transactions to FLUSABLE_DB_XX instead of TEST_DB_XX. 

I always confused TEST_SITE_DB_NAME and TEST_DB_NAME and entered the wrong data haha. 

Also, may I ask on that point why the required codeception modules are not in the "require" section?. These are clearly not optional as you cant install wp-browser without then.

**Comment by lucatume** [comment]
> Yea I get why you`d run them separately. Still annoying tho. My "fix" is working fine tho. Testing this for two days.
> 
> Do you want me to commit a pr?.

I would like to try this out on my own testing some lesser common scenarios; if your fix could solve your problem while not introducing others, it would be great.
 
> I renamed the database that gets flushed during transactions to FLUSABLE_DB_XX instead of TEST_DB_XX.
> 
> I always confused TEST_SITE_DB_NAME and TEST_DB_NAME and entered the wrong data haha.

Naming things is hard: different people will call things in different ways and there was a lot of drama, at one point, over how to call what. Once one gets the naming of env vars is not set in stone, but merely an initial suggestion, it clicks.
I'm always open to suggestions on this front, though.
 
> Also, may I ask on that point why the required codeception modules are not in the "require" section?. These are clearly not optional as you cant install wp-browser without then.

Because wp-browser has to be compatible with Codeception 2.5, 3.0, and 4.0. I would not drop back compatibility if I can keep being compatible with the older versions. 
I know of a number of projects that still use 2.5.
What I've been wondering for a bit is to, during the setup of the template (`codecept init wpbrowser`), pickup. the Codeception version and, if 4.0, prompt the user to update the `composer.json` file for them. 
Might be a way to mitigate this.

**Comment by calvinalkan** [comment]
There is still one issue with my solution being that the first time you run a WpTestCase the `_setUpBeforeClass` method is not executed because the variable is only set later in `_setUp()`. 

Maybe we could use codeceptions suite bootstrap files. But they need to be executed because the test case or it wont work. 


Another question @lucatume. 

I notice that when I run tests that extend with `WpTestCase` with phpunit instead of codeception, the execution is way faster. More or less 500ms less in fact. Running it with phpunit we obv don't load codeception and the `WpLoader`module but I'm still surprised by that difference. 

When I just need Wordpress to be loaded for functions what are the benefits that `WpLoader` gives me instead of just using `WpTestCase` which seems to bootstrap everything just fine aswell.

**Comment by lucatume** [comment]
> There is still one issue with my solution being that the first time you run a WpTestCase the `_setUpBeforeClass` method is not executed because the variable is only set later in `_setUp()`.
> 
> Maybe we could use codeceptions suite bootstrap files. But they need to be executed because the test case or it wont work.

The issue here is that the solution would make running all the tests using `codecept run` possible only in a set of scenarios where the only tests set up are unit and integration using the `WPLoader` module.
WordPress use of globals and side-effects would make itself apparent by means of constants and globals making the whole experience pretty miserable.
I'm willing to explore the solution, but I would not be able to say "now you can run all the tests at the same time and not run into issues" at the end anyway.
Errors are actually good as they break the tests and clearly show there is an issue; debugging failures, or passes, related to side effects set up by previous runs of tests in other suites is even worse.

> Another question @lucatume.
> 
> I notice that when I run tests that extend with `WpTestCase` with phpunit instead of codeception, the execution is way faster. More or less 500ms less in fact. Running it with phpunit we obv don't load codeception and the `WpLoader`module but I'm still surprised by that difference.
> 
> When I just need Wordpress to be loaded for functions what are the benefits that `WpLoader` gives me instead of just using `WpTestCase` which seems to bootstrap everything just fine as well.

Codeception is a big guy and will do a lot of stuff and open a lot of doors that make extending and integrating with it, faster.
When the test suite grows in size and complexity and type of testing, then those benefits will pay. 
WPLoader works with PHPUnit as it's in essence, a repurposed version of the WordPress PHPUnit-based Core test suite, and I took some pain in making sure it would keep working in PHPUnit context without loss if someone is not using the APIs provided by Codeception (extensions, modules and the like). 
It's not an accident it does, and I'm glad it solves your problem in this specific context.

**Comment by lucatume** [comment]
@calvinalkan what's the status on this? I would like to either test a PR for this or close the issue.

**Comment by calvinalkan** [comment]
@lucatume Yes please, go ahead and close this for now. If I get to it in the future Ill submit a PR.
