### ISSUE TITLE
Requiring wp-browser causes WordPress to throw an error

### ISSUE THREAD

**Issue by BrandonBraner** [lucatume/wp-browser#56]
```
Fatal error: Call to undefined method Requests_Response::is_redirect() in /Applications/MAMP/htdocs/wordpress/wp-includes/class-requests.php on line 685
```

After I require wp-browser in composer I then get this error when trying to access my site. If I remove wp-browser everything works fine.
Tried on php 5.5, 5.6, and 7.0
WordPress version 4.6.1

**Comment by lucatume** [comment]
Could you post your `composer.json` file?
If you cannot at least the `require` and `require-dev` sections of your `composer.json` file, thanks.

**Comment by BrandonBraner** [comment]
Here is a link to an image with the full error stack.
http://screencast.com/t/s4MQtGdp
```
{
    "name": "leadpages/leadpagesconnector",
    "description": "Leadpages WordPress connector",
    "require": {
        "pimple/pimple": "^3.0",
        "leadpages/leadpages-auth": "*",
        "leadpages/pages": "*",
        "leadpages/leadboxes": "*",
        "icanboogie/inflector": "^1.4",
        "ramsey/uuid": "^2.9",
        "moontoast/math": "*"
    },
    "require-dev": {
        "codeception/codeception": "^2.2",
        "site5/phantoman": "^1.1",
        "jakoch/phantomjs-installer": "2.1.1-p06",
        "lucatume/wp-browser": "~1.16"
    },
    "autoload": {
        "psr-4": {
            "TheLoop\\": "Framework//",
            "LeadpagesWP\\": "App//",
            "LeadpagesMetrics\\": "App//Lib//LeadpagesMetrics//"
        }
    },
    "authors": [
        {
            "name": "Brandon Braner",
            "email": "brandon.braner@ave81.com"
        }
    ],
    "scripts": {
        "post-install-cmd": [
            "PhantomInstaller\\Installer::installPhantomJS"
        ],
        "post-update-cmd": [
            "PhantomInstaller\\Installer::installPhantomJS"
        ]
    }
}
```

**Comment by lucatume** [comment]
I've created an empty plugin using your configuration file and run `composer install`.
The class `Request_Response` is part of the `rmccue/requests` package; that's not a package `wp-browser` uses.
The `rmccue/requests` package is but used from the `wp-cli/wp-cli` package that is, in turn, required by `wp-browser`.
The `Requests_Response::is_redirect()` method is not part of version `1.6.1` of `rmccue/requests` but it's instead part of `master`; I guess one of the packages you use requires it like:   

```json
"rmccue/requests": "dev-master"
```

`wp-cli/wp-cli` requires `rmccue/requests` stable version `~1.6` and will hence download that and not the `dev-master` one: that's why the `Requests_Response::is_redirect()` will not be there.  

The "trick" is to alias `rmccue/requests` `dev-master` branch to a version that's compatible with `wp-cli/wp-cli` requirement of `~1.6` like this (I'm reporting the modified `require` section of your `composer.json` file only):

 ```json
"require": {
    "pimple/pimple": "^3.0",
    "leadpages/leadpages-auth": "*",
    "leadpages/pages": "*",
    "leadpages/leadboxes": "*",
    "icanboogie/inflector": "^1.4",
    "ramsey/uuid": "^2.9",
    "moontoast/math": "*",
    "rmccue/requests": "dev-master as 1.6.2beta"
}, 
 ```
 
In the end this is not a `wp-browser` issue as it's not any other package issue, it's a simple version requirement conflict.

**Comment by lucatume** [comment]
Any news here? Did the proposed solution above help you?

**Comment by BrandonBraner** [comment]
It appears to yes.
Thank you

**Comment by lucatume** [comment]
Thanks for taking the time to open an issue and follow through, much appreciated.
