### ISSUE TITLE
[FEATURE REQUEST] Implement wp-test-utils for unit and integration tests

### ISSUE THREAD

**Issue by dingo-d** [lucatume/wp-browser#643]
**Is your feature request related to a problem? Please describe.**
[wp-test-utils](https://github.com/Yoast/wp-test-utils) is a library that will make it easy to run integration and unit tests for plugins and themes in a  cross-version compatible way.

The main advantage is that it covers a wide range of PHP and PHPUnit versions, and has a built-in [BrainMonkey](https://packagist.org/packages/brain/monkey) test suite (which is ideal for unit testing).

**Describe the solution you'd like**
Unit and Integration tests should extend the classes, and have out of the box setup that is compatible with wp-test-utils.

**Comment by lucatume** [comment]
I don't know what gap this addition would fill.

If you want to write unit tests in the commonly-understood way (total isolation, total mocking), you can `vendor/bin/codecept generate:test` and use whatever library you require.
If you want to write integration or unit tests in a less commonly understood way, wp-browser will load WordPress, themes, and plugins for you in an as-easy-as-I-could-make-it way.
Same for end-to-end tests.

Regarding function mocking, I'm fully aware of the current solutions, including BrainMonkey.
I'm intimate with how it works since both that and [function-mocker](https://github.com/lucatume/function-mocker) build on the Patchwork framework.
I think [the `uopz` extension](https://github.com/krakjoe/uopz) is a better all-around solution, with great performance and immense power. With containerized builds, including that extension in a shared environment is easy.
Note that [I use that in testing this very project](https://github.com/lucatume/wp-browser/blob/master/tests/_support/Traits/UopzFunctions.php).
Furthermore, to not require an extension and still pull its isolated process magic, wp-browser [has its own stream-wrapping implementation](https://github.com/lucatume/wp-browser/blob/master/src/MonkeyPatch/FileStreamWrapper.php) (Patchwork is a `file://` stream wrapper), so I would rather build on that to provide a built-in solution.

As mentioned at the start of this answer, I'm not opinionated enough about how one should go about testing to intentionally block any other available solution in wp-browser; if they do not work, it's not by design.
The list of components I've rebuilt myself, whether they are apparent or not to users of the library, are an indication of how much I try to keep the number of dependencies and the opinionated approach some of those dependencies come with, to a minimum.

Regarding covering a wide range of PHP and PHPUnit versions, this project, in its versions 3 and 4, covers PHP 5.6 to 8.2 and PHPUnit 6 to 10.

Is there something you tried that failed?

**Comment by dingo-d** [comment]
Thanks for the extensive answer!

I just thought that it might be beneficial to use this lib, as it's made to work really well with WordPress native test suite (apart from PHPUnit 10 version which is a problem for integration tests).

I am currently testing it out for Unit tests, so it could be added for that use case (the bundled test case has BrainMonkey already implemented so it would be useful).

**Comment by lucatume** [comment]
If needed, you can add it on a per-project basis; only some write that type of unit test, so I'm not inclined to include it by default.

If adding that as a dev requirement makes things explode, I could look into that.
