### ISSUE TITLE
[FEATURE REQUEST] Lock WordPress to Specific Version

### ISSUE THREAD

**Issue by tarecord** [lucatume/wp-browser#719]
**Is your feature request related to a problem? Please describe.**
Whenever WordPress core updates, wp-browser downloads the latest version which sometimes breaks SQLite compatibility with an error like:
```
 Installing WordPress in tests/_wordpress ...
 WordPress installation failed. Error: WordPress 6.5.2 requires MySQL 5.5.5 or higher 
 Setup failed, check the error message above and try again. 
```

**Describe the solution you'd like**
Adding the ability to define the version of WordPress installed in the test directory would keep automated tests running successfully and allow projects to update test environments as needed.

**Describe alternatives you've considered**
The only alternative would be to commit the downloaded `tests/_wordpress` folder, but that would massively increase the size of project repositories unnecessarily

**Additional context**
Tests failing in a GitHub action due to new WordPress version (`6.5.2`):

![CleanShot 2024-04-12 at 11 54 04@2x](https://github.com/lucatume/wp-browser/assets/6947218/0ef9bf1e-2169-485c-9772-80b8a3f3091c)

**Comment by lucatume** [comment]
HI @tarecord,

thanks for taking the time to open an issue.

I'm not sure I understand your use case: you're running `vendor/bin/codecept init wpbrowser` in a CI action? What is the use case for this?

Aside from this, if I understand correctly, you would like to be able to specify the WordPress version **during initialization**, right?

The `vendor/bin/codecept init ...` command does not allow custom arguments or options (e.g. a `--version` option), so it would need to be a question, but in CI context this would not work since the command will not be interactive and the question would default (to `latest` as it is now).

I will look into this and check what options are there for this, likely an env var, like this:
```bash
WP_VERSION=6.4.1 vendor/bin/codecept init wpbrowser
```
Which is not great, but would still work.

**Comment by tarecord** [comment]
I may be misunderstanding how this should be used in a CI environment, but I'm using `vendor/bin/codecept init wpbrowser` to set up and configure the portable PHP server, SQLite DB, and Chromedriver environment. (If there's a better way, please let me know)

Could the WP version be defined in `codeception.yml`?

**Comment by lucatume** [comment]
The `vendor/bin/codecept init wpbrowser` commad should be used locally, only once, when first setting up the project to use Codeception and  wp-browser.
The now set up project is, then, pushed to the CI, where a second `init wpbrowser` will not be required and will, actually, fail.
Once set up locally, the project will just work in CI.
[You can see an example from wp-browser own test workflow here.](https://github.com/lucatume/wp-browser/blob/master/.github/workflows/test.yaml)


> Could the WP version be defined in codeception.yml?

The WP version cannot be defined in the `codeception.yml` file since the `codeception.yml` file will not be there when the `vendor/bin/codecept init wpbrowser` command runs: the `vendor/bin/codeception init wpbrowser` command will set up Codeception and wp-browser to test the project, scaffold all files and directories

**Comment by lucatume** [comment]
Closing after meeting to discuss the issue.
